"""Single-prompt structured-event extractor for the four key ExECTv2 families.

Thin facade over the ``pipelines/key_entities_structured/`` package. Every
public symbol is re-exported so existing importers keep working. Private
helpers and the ``parse_json_payload_with_schema_repair`` / ``write_jsonl``
pass-throughs are also re-exported because other modules import this module as
``structured`` and access those attributes directly.

After the 2026-08-16 prune, live identities are ``v0.9.24`` and
cheap-stack ``v0.9.40``. Study-only further-prune IDs sit beside them.
"""
# ruff: noqa: F401 — thin re-export facade; all symbols are intentionally re-exported.

from .pipelines.key_entities_structured import (
    _DIAGNOSIS_RE,
    _INVESTIGATION_RE,
    _MEDICATION_RE,
    _SEIZURE_STATE_RE,
    _SF_STATE_ATTRS,
    ALLOWED_EVENT_FAMILIES,
    COMPONENT_OWNER,
    KEY_ENTITY_ITEM_F1_TARGET,
    KEY_ENTITY_NAMES,
    PIPELINE_FAMILY,
    PROMPT_VERSION,
    PROMPT_VERSION_V0_9_24,
    PROMPT_VERSION_V0_9_40_DROP_ENCODING_NON_SF_ALL_EXAMPLES,
    PROMPT_VERSION_V0_9_41_CHEAP_DROP_IX_PENDING_REPEAT,
    PROMPT_VERSION_V0_9_42_CHEAP_DROP_SCAFFOLD_REPRINT,
    PROMPT_VERSION_V0_9_43_CHEAP_COLLAPSE_REFUSE,
    PROMPT_VERSION_V0_9_44_CHEAP_STACK_FURTHER_PRUNES,
    PUBLISHED_PER_ENTITY_ITEM_F1,
    DspyKeyEntitiesStructuredExtractor,
    EventFamily,
    ExECTv2KeyEntitiesStructuredSignature,
    MedicationHistoryRecord,
    MentionForEvidence,
    PatientHistoryRecord,
    PromptProfile,
    RenderedMentionRecord,
    StructuredClinicalEvent,
    StructuredExtractionRecord,
    __all__,
    _apply_render_safety_gates,
    _attribute_vocabulary,
    _checkpoint_report_path,
    _clinical_recovery_lines,
    _coerce_structured_payload,
    _decision_procedure,
    _diagnosis_lane_hint,
    _diagnostic_ladder_lines,
    _drop_duplicate_modality_only_investigations,
    _emit_checkpoint,
    _event_lane_guide,
    _family_guidance,
    _first_match_text,
    _has_investigation_result,
    _has_sf_state,
    _investigation_lane_hint,
    _investigation_modalities,
    _key_clinical_recovery_to_dict,
    _legacy_mention_to_event,
    _medication_lane_hint,
    _mention_to_row,
    _overall_to_dict,
    _prf1_to_dict,
    _reconstruct_letters,
    _repair_evidence_from_mention_text,
    _score_lines,
    _seizure_anchor_hint,
    _seizure_frequency_lane_hint,
    _sentence_spans,
    _source_near_to_dict,
    _stringify_mapping,
    _strip_model_supplied_projection_attrs,
    _strip_non_scored_rationale_fields,
    _worked_examples,
    build_prompt_input,
    candidate_evidence_ledger_for_letter,
    flatten_events,
    format_retry_schema_for,
    high_priority_evidence_ledger_for_letter,
    parse_json_payload_with_schema_repair,
    parse_structured_events_json,
    prompt_version_for,
    run_split,
    set_active_prompt_version,
    summarize_rows,
    to_predicted_letter,
    write_jsonl,
    write_report,
)

__all__ = list(__all__)
