"""Single-prompt structured-event extractor for the four key ExECTv2 families.

Thin facade over the ``pipelines/key_entities_structured/`` package. Every
public symbol is re-exported so existing importers keep working. Private
helpers and the ``parse_json_payload_with_schema_repair`` / ``write_jsonl``
pass-throughs are also re-exported because other modules import this module as
``structured`` and access those attributes directly.
"""
# ruff: noqa: F401 — thin re-export facade; all symbols are intentionally re-exported.

from .pipelines.key_entities_structured import (
    _DIAGNOSIS_RE,
    _INVESTIGATION_RE,
    _MEDICATION_RE,
    _SEIZURE_STATE_RE,
    _SF_STATE_ATTRS,
    ALLOWED_EVENT_FAMILIES,
    COMPONENT_OWNER,
    KEY_ENTITY_ITEM_F1_TARGET,
    KEY_ENTITY_NAMES,
    PIPELINE_FAMILY,
    PROMPT_VERSION,
    PROMPT_VERSION_V0_9_24,
    PROMPT_VERSION_V0_9_25_LUNA_SF_BOUNDARY_DX,
    PROMPT_VERSION_V0_9_25_LUNA_SF_STATE,
    PROMPT_VERSION_V0_9_26_DROP_SCAFFOLD,
    PROMPT_VERSION_V0_9_27_DROP_EXAMPLES,
    PROMPT_VERSION_V0_9_28_DROP_ENCODING_RULES,
    PROMPT_VERSION_V0_9_29_DROP_SCOPE_RULES,
    PROMPT_VERSION_V0_9_30_DROP_SCAFFOLD_EXAMPLES,
    PROMPT_VERSION_V0_9_31_DROP_SCAFFOLD_EXAMPLES_ENCODING,
    PROMPT_VERSION_V0_9_32_DROP_SCOPE_SF_REFUSE,
    PROMPT_VERSION_V0_9_33_DROP_SCOPE_SF_KEEP,
    PROMPT_VERSION_V0_9_34_DROP_SCOPE_DIAGNOSIS,
    PROMPT_VERSION_V0_9_35_DROP_SCOPE_RX_IX,
    PROMPT_VERSION_V0_9_36_DROP_ENCODING_NON_SF,
    PROMPT_VERSION_V0_9_37_DROP_EXAMPLES_NON_SF,
    PROMPT_VERSION_V0_9_38_DROP_EXAMPLES_SF_ENCODING,
    PROMPT_VERSION_V0_9_39_DROP_EXAMPLES_SF_SCOPE,
    PROMPT_VERSION_V10,
    PROMPT_VERSION_V11,
    PROMPT_VERSION_V12,
    PROMPT_VERSION_V13,
    PROMPT_VERSION_V14,
    PROMPT_VERSION_V15,
    PROMPT_VERSION_V16,
    PROMPT_VERSION_V17,
    PROMPT_VERSION_V18,
    PROMPT_VERSION_V19,
    PROMPT_VERSION_V20,
    PROMPT_VERSION_V21,
    PROMPT_VERSION_V22,
    PROMPT_VERSION_V23,
    PROMPT_VERSION_V24,
    PROMPT_VERSION_V25,
    PROMPT_VERSION_V26,
    PROMPT_VERSION_V27,
    PUBLISHED_PER_ENTITY_ITEM_F1,
    QWEN_COMPACT_PROMPT_VERSION,
    DspyKeyEntitiesStructuredExtractor,
    EventFamily,
    ExECTv2KeyEntitiesStructuredSignature,
    ExECTv2KeyEntitiesStructuredSignatureV26,
    MedicationHistoryRecord,
    MentionForEvidence,
    PatientHistoryRecord,
    PromptProfile,
    RenderedMentionRecord,
    StructuredClinicalEvent,
    StructuredExtractionRecord,
    V26StructuredExtractionRecord,
    __all__,
    _apply_render_safety_gates,
    _attribute_vocabulary,
    _build_qwen_compact_prompt_input,
    _checkpoint_report_path,
    _clinical_recovery_lines,
    _coerce_structured_payload,
    _decision_procedure,
    _diagnosis_lane_hint,
    _diagnostic_ladder_lines,
    _drop_duplicate_modality_only_investigations,
    _emit_checkpoint,
    _event_lane_guide,
    _family_guidance,
    _first_match_text,
    _has_investigation_result,
    _has_sf_state,
    _investigation_lane_hint,
    _investigation_modalities,
    _key_clinical_recovery_to_dict,
    _legacy_mention_to_event,
    _medication_lane_hint,
    _mention_to_row,
    _overall_to_dict,
    _prf1_to_dict,
    _qwen_compact_examples,
    _reconstruct_letters,
    _repair_evidence_from_mention_text,
    _score_lines,
    _seizure_anchor_hint,
    _seizure_frequency_lane_hint,
    _sentence_spans,
    _source_near_to_dict,
    _stringify_mapping,
    _strip_model_supplied_projection_attrs,
    _strip_non_scored_rationale_fields,
    _worked_examples,
    build_prompt_input,
    candidate_evidence_ledger_for_letter,
    flatten_events,
    format_retry_schema_for,
    high_priority_evidence_ledger_for_letter,
    parse_json_payload_with_schema_repair,
    parse_structured_events_json,
    prompt_version_for,
    run_split,
    set_active_prompt_version,
    summarize_rows,
    to_predicted_letter,
    write_jsonl,
    write_report,
)

__all__ = list(__all__)
