"use client";

import { useCallback, useMemo, useState } from "react";
import { Download, FileText, Check } from "lucide-react";
import { tableToMarkdown } from "./PaperTable";

interface ReportSection {
  title: string;
  headers: string[];
  rows: (string | number | null)[][];
  align?: ("left" | "right" | "center")[];
}

interface ExportPanelProps {
  sections: ReportSection[];
  runIds: string[];
  metadata?: {
    generatedAt?: string;
    url?: string;
  };
}

function buildFullReport(sections: ReportSection[], runIds: string[], metadata?: ExportPanelProps["metadata"]): string {
  const lines: string[] = [];
  lines.push("---");
  lines.push(`title: "Clinical Extraction Observatory Report"`);
  lines.push(`date: ${metadata?.generatedAt ?? new Date().toISOString()}`);
  lines.push(`runs: [${runIds.map((id) => `"${id}"`).join(", ")}]`);
  if (metadata?.url) lines.push(`url: ${metadata.url}`);
  lines.push("---");
  lines.push("");
  lines.push("# Clinical Extraction Observatory – Research Report");
  lines.push("");
  lines.push(
    "> This report was generated automatically from the Clinical Extraction Observatory. " +
      "All numbers are traceable to specific run artifacts. Locked-test results require a frozen predeclared protocol."
  );
  lines.push("");

  for (const section of sections) {
    if (section.rows.length === 0) continue;
    lines.push(tableToMarkdown(section.title, section.headers, section.rows, section.align));
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by Clinical Extraction Observatory*");
  return lines.join("\n");
}

export default function ExportPanel({ sections, runIds, metadata }: ExportPanelProps) {
  const [copied, setCopied] = useState(false);
  const report = useMemo(
    () => buildFullReport(sections, runIds, metadata),
    [sections, runIds, metadata]
  );

  const handleDownload = useCallback(() => {
    const blob = new Blob([report], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `observatory_report_${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [report]);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(report).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  }, [report]);

  return (
    <div className="rounded-lg border border-border bg-surface p-4 space-y-3">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-xs font-semibold uppercase tracking-wider text-foreground">
            Report Assembly
          </h3>
          <p className="text-[11px] text-muted mt-0.5">
            {sections.filter((s) => s.rows.length > 0).length} tables · {runIds.length} runs
          </p>
        </div>
        <div className="flex items-center gap-1.5">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1 rounded-md border border-border bg-surface-raised px-2.5 py-1.5 text-[11px] font-medium text-muted hover:text-foreground transition-colors"
          >
            {copied ? <Check className="h-3 w-3 text-success" /> : <FileText className="h-3 w-3" />}
            {copied ? "Copied" : "Copy full report"}
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-1 rounded-md border border-deterministic bg-deterministic px-2.5 py-1.5 text-[11px] font-medium text-surface transition-colors hover:bg-deterministic/90"
          >
            <Download className="h-3 w-3" />
            Download .md
          </button>
        </div>
      </div>
      <div className="space-y-1">
        {sections.map((s) => (
          <div key={s.title} className="flex items-center gap-2 text-[11px]">
            <span
              className={`h-1.5 w-1.5 rounded-full ${
                s.rows.length > 0 ? "bg-success" : "bg-muted"
              }`}
            />
            <span className={s.rows.length > 0 ? "text-foreground" : "text-muted line-through"}>
              {s.title}
            </span>
            <span className="text-muted">({s.rows.length} rows)</span>
          </div>
        ))}
      </div>
    </div>
  );
}
