"""Build the gan2026 side of the shared reliability scorecard."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from clinical_extraction.core.shared_reliability_schema import (
    SIX_MODELS,
    make_record,
)


@dataclass(frozen=True)
class GanMeasurementInputs:
    artifact_index: Any
    common_gan: Any
    component_path: Any
    component_summary: Any
    gan_calibration: Any
    gan_consistency: Any
    gan_coverage: Any
    gan_grounding: Any
    gan_master_path: Any
    gan_operations: Any
    gan_ops: Any
    gan_overread: Any
    gan_pragmatic: Any
    gan_purist: Any
    gan_risk: Any
    gan_robustness: Any
    gan_test: Any
    gan_val: Any
    hosted_path: Any


def build_gan2026_measurements(inputs: GanMeasurementInputs) -> list[dict[str, Any]]:
    """Return retained gan2026 measurements without rescoring or model calls."""

    return [
        make_record(
            **inputs.common_gan,
            criterion_id="clinical_correctness_generalization",
            measurement_id="gan2026_six_model_test450_purist_accuracy",
            model_scope=SIX_MODELS,
            split="test450",
            row_scope="aggregate_only_rows_sealed",
            denominator=450,
            denominator_status="defined",
            unit="correct_labels_and_accuracy",
            score_stage="final",
            scorer="Gan 2026 Purist label accuracy",
            repair_policy="hybrid_full_stack",
            value=inputs.gan_purist,
            evidence_state="aggregate_holdout_evidence",
            comparability="construct_only",
            source_artifacts=[inputs.hosted_path],
            claim_boundary=(
                "Matched aggregate-only v0.5 panel; not a pristine one-shot or "
                "model-neutral ranking."
            ),
            prompt_program="gan2026_hybrid_structured_events_v0.5",
            reproducibility_command="python scripts/verify_reference_evidence.py",
            unique_rows=450,
            model_row_count=2700,
        ),
        make_record(
            **inputs.common_gan,
            criterion_id="clinical_correctness_generalization",
            measurement_id="gan2026_six_model_test450_pragmatic_accuracy",
            model_scope=SIX_MODELS,
            split="test450",
            row_scope="aggregate_only_rows_sealed",
            denominator=450,
            denominator_status="defined",
            unit="correct_labels_and_accuracy",
            score_stage="final",
            scorer="Gan 2026 Pragmatic label accuracy",
            repair_policy="hybrid_full_stack",
            value=inputs.gan_pragmatic,
            evidence_state="aggregate_holdout_evidence",
            comparability="construct_only",
            source_artifacts=[inputs.hosted_path],
            claim_boundary=(
                "Secondary aggregate-only v0.5 score; task-specific and not pooled with ExECT F1."
            ),
            prompt_program="gan2026_hybrid_structured_events_v0.5",
            reproducibility_command="python scripts/verify_reference_evidence.py",
            unique_rows=450,
            model_row_count=2700,
        ),
        make_record(
            artifact_index=inputs.artifact_index,
            task="gan2026",
            criterion_id="clinical_correctness_generalization",
            measurement_id="gan2026_subject_validation750_purist_accuracy",
            model_scope=["openai/gpt-4.1-mini v0_reference subject"],
            split="dev750",
            row_scope="development_rows_permitted",
            denominator=750,
            denominator_status="defined",
            unit="accuracy",
            score_stage="final",
            scorer="Gan 2026 Purist label accuracy",
            repair_policy="retained v0_reference policy",
            value=inputs.gan_val,
            evidence_state="development_answer",
            comparability="construct_only",
            source_artifacts=[inputs.gan_master_path],
            claim_boundary=(
                "Named historical subject only; not the matched six-model validation panel."
            ),
            route_runtime="openai/gpt-4.1-mini retained subject",
            temperature="not_recorded_in_compact_scorecard",
            token_limit="not_recorded_in_compact_scorecard",
            cache_replay_mode="retained no-call summary",
            prompt_program="v0_reference",
            row_inspection_rule="dev750 rows permitted",
            locked_row_controls="not a locked split",
            independent_clinical_review="not_completed",
            reproducibility_command="python scripts/check_retained_evidence_manifest.py",
            pooling_unit="letter",
            unique_rows=750,
            model_row_count=750,
        ),
        make_record(
            artifact_index=inputs.artifact_index,
            task="gan2026",
            criterion_id="clinical_correctness_generalization",
            measurement_id="gan2026_subject_test450_purist_accuracy",
            model_scope=["openai/gpt-4.1-mini v0_reference subject"],
            split="test450",
            row_scope="aggregate_only_rows_sealed",
            denominator=450,
            denominator_status="defined",
            unit="accuracy",
            score_stage="final",
            scorer="Gan 2026 Purist label accuracy",
            repair_policy="retained v0_reference policy",
            value=inputs.gan_test,
            evidence_state="aggregate_holdout_evidence",
            comparability="construct_only",
            source_artifacts=[inputs.gan_master_path],
            claim_boundary=(
                "Named historical subject aggregate only; not the selected matched six-model "
                "v0.5 panel."
            ),
            route_runtime="openai/gpt-4.1-mini retained subject",
            temperature="not_recorded_in_compact_scorecard",
            token_limit="not_recorded_in_compact_scorecard",
            cache_replay_mode="retained no-call summary",
            prompt_program="v0_reference",
            row_inspection_rule="aggregate-only test450; no locked-row inspection",
            locked_row_controls="test450 rows sealed; aggregate values only",
            independent_clinical_review="not_completed",
            reproducibility_command="python scripts/check_retained_evidence_manifest.py",
            pooling_unit="letter",
            unique_rows=450,
            model_row_count=450,
        ),
        make_record(
            artifact_index=inputs.artifact_index,
            task="gan2026",
            criterion_id="clinical_selection_unsupported_inference",
            measurement_id="gan2026_unknown_gold_active_rate_overread_rate",
            model_scope=["openai/gpt-4.1-mini v0_reference subject"],
            split="dev750+test450",
            row_scope="aggregate_only_rows_sealed",
            denominator=None,
            denominator_status="unknown-gold counts not retained in selected compact scorecard",
            unit="rate",
            score_stage="final",
            scorer="Gan unknown-gold active-rate over-read transform",
            repair_policy="retained v0_reference policy",
            value={"validation750": inputs.gan_overread[0], "test450": inputs.gan_overread[1]},
            evidence_state="aggregate_holdout_evidence",
            comparability="not_comparable",
            source_artifacts=[inputs.gan_master_path],
            claim_boundary=(
                "Retained subject rates; selected compact artifact lacks denominator counts."
            ),
            route_runtime="openai/gpt-4.1-mini retained subject",
            temperature="not_recorded_in_compact_scorecard",
            token_limit="not_recorded_in_compact_scorecard",
            cache_replay_mode="retained no-call summary",
            prompt_program="v0_reference",
            row_inspection_rule="dev750 rows permitted; test450 aggregate only",
            locked_row_controls="test450 rows sealed; no failure analysis",
            independent_clinical_review="not_completed",
            reproducibility_command="python scripts/check_retained_evidence_manifest.py",
            pooling_unit="unknown_gold_letter",
            unique_rows=None,
            model_row_count=None,
        ),
        make_record(
            artifact_index=inputs.artifact_index,
            task="gan2026",
            criterion_id="evidence_support_faithfulness",
            measurement_id="gan2026_textual_grounding_rate",
            model_scope=["openai/gpt-4.1-mini v0_reference subject"],
            split="dev750+test450",
            row_scope="aggregate_only_rows_sealed",
            denominator={"validation750": 750, "test450": 450},
            denominator_status="defined",
            unit="exact_grounding_rate",
            score_stage="final",
            scorer="Gan retained faithfulness transform",
            repair_policy="retained v0_reference policy",
            value={"validation750": inputs.gan_grounding[0], "test450": inputs.gan_grounding[1]},
            evidence_state="aggregate_holdout_evidence",
            comparability="construct_only",
            source_artifacts=[inputs.gan_master_path],
            claim_boundary=(
                "Textual grounding at the retained final stage; not independent semantic support."
            ),
            route_runtime="openai/gpt-4.1-mini retained subject",
            temperature="not_recorded_in_compact_scorecard",
            token_limit="not_recorded_in_compact_scorecard",
            cache_replay_mode="retained no-call summary",
            prompt_program="v0_reference",
            row_inspection_rule="dev750 rows permitted; test450 aggregate only",
            locked_row_controls="test450 rows sealed",
            independent_clinical_review="not_completed",
            reproducibility_command="python scripts/check_retained_evidence_manifest.py",
            pooling_unit="letter",
            unique_rows=1200,
            model_row_count=1200,
        ),
        make_record(
            artifact_index=inputs.artifact_index,
            task="gan2026",
            criterion_id="evidence_support_faithfulness",
            measurement_id="gan2026_semantic_support_review",
            model_scope=["not_selected"],
            split="not_measured",
            row_scope="synthetic_fixture",
            denominator=None,
            denominator_status="not_measured",
            unit="semantic_support_rate",
            score_stage="final",
            scorer="independent clinical review",
            repair_policy="not_applicable",
            value=None,
            evidence_state="not_measured",
            comparability="construct_only",
            source_artifacts=[inputs.gan_master_path],
            claim_boundary="No independent semantic-support result is claimed.",
            route_runtime="not_applicable",
            temperature="not_applicable",
            token_limit="not_applicable",
            cache_replay_mode="not_applicable",
            prompt_program="not_applicable",
            row_inspection_rule="no review rows selected",
            locked_row_controls="test450 rows remain sealed",
            independent_clinical_review="not_started",
            reproducibility_command="python scripts/check_retained_evidence_manifest.py",
            pooling_unit="review_item",
            unique_rows=None,
            model_row_count=None,
            result_state="not_measured",
            not_measured_reason=(
                "No independently reviewed semantic-support substrate is selected for Gan."
            ),
        ),
        make_record(
            artifact_index=inputs.artifact_index,
            task="gan2026",
            criterion_id="uncertainty_selective_action",
            measurement_id="gan2026_external_signal_calibration",
            model_scope=["openai/gpt-4.1-mini v0_reference subject"],
            split="dev750",
            row_scope="development_rows_permitted",
            denominator=750,
            denominator_status="defined_subject_rows",
            unit="calibration_and_failure_detection",
            score_stage="final",
            scorer="Gan external-confidence calibration transform",
            repair_policy="retained v0_reference policy",
            value={
                "ece": inputs.gan_calibration[0],
                "brier": inputs.gan_calibration[1],
                "failure_auroc": inputs.gan_calibration[2],
            },
            evidence_state="development_answer",
            comparability="construct_only",
            source_artifacts=[inputs.gan_master_path],
            claim_boundary=(
                "External-signal result for the named subject; not model self-confidence "
                "or deployment calibration."
            ),
            route_runtime="openai/gpt-4.1-mini retained subject",
            temperature="not_recorded_in_compact_scorecard",
            token_limit="not_recorded_in_compact_scorecard",
            cache_replay_mode="retained no-call summary",
            prompt_program="v0_reference",
            row_inspection_rule="dev750 rows permitted",
            locked_row_controls="not a locked split",
            independent_clinical_review="not_completed",
            reproducibility_command="python scripts/check_retained_evidence_manifest.py",
            pooling_unit="letter",
            unique_rows=750,
            model_row_count=750,
        ),
        make_record(
            artifact_index=inputs.artifact_index,
            task="gan2026",
            criterion_id="uncertainty_selective_action",
            measurement_id="gan2026_risk_coverage",
            model_scope=["openai/gpt-4.1-mini v0_reference subject"],
            split="dev750",
            row_scope="development_rows_permitted",
            denominator=750,
            denominator_status="defined_subject_rows",
            unit="risk_coverage",
            score_stage="final",
            scorer="Gan retained risk-coverage transform",
            repair_policy="retained v0_reference policy",
            value={
                "auc": inputs.gan_risk[0],
                "oracle_auc": inputs.gan_risk[1],
                "risk_at_50pct_coverage": inputs.gan_risk[2] / 100,
                "risk_at_80pct_coverage": inputs.gan_risk[3] / 100,
            },
            evidence_state="development_answer",
            comparability="construct_only",
            source_artifacts=[inputs.gan_master_path],
            claim_boundary="Named validation subject only; no deployment review policy is implied.",
            route_runtime="openai/gpt-4.1-mini retained subject",
            temperature="not_recorded_in_compact_scorecard",
            token_limit="not_recorded_in_compact_scorecard",
            cache_replay_mode="retained no-call summary",
            prompt_program="v0_reference",
            row_inspection_rule="dev750 rows permitted",
            locked_row_controls="not a locked split",
            independent_clinical_review="not_completed",
            reproducibility_command="python scripts/check_retained_evidence_manifest.py",
            pooling_unit="letter",
            unique_rows=750,
            model_row_count=750,
        ),
        make_record(
            artifact_index=inputs.artifact_index,
            task="gan2026",
            criterion_id="robustness_stability",
            measurement_id="gan2026_prompt_version_robustness_index",
            model_scope=["openai/gpt-4.1-mini retained prompt subjects"],
            split="dev750+test450_aggregate",
            row_scope="aggregate_only_rows_sealed",
            denominator=None,
            denominator_status="index_transform_not_a_rate_denominator",
            unit="robustness_index",
            score_stage="final",
            scorer="Gan retained prompt-version robustness transform",
            repair_policy="version-specific retained policies",
            value={
                "direct_labeler_v0_5": inputs.gan_robustness[0],
                "evidence_v0_6": inputs.gan_robustness[1],
                "evidence_v0_7": inputs.gan_robustness[2],
            },
            evidence_state="diagnostic",
            comparability="construct_only",
            source_artifacts=[inputs.gan_master_path],
            claim_boundary=(
                "Prompt-version subdimension only; overfit-gap is diagnostic and not "
                "broad robustness."
            ),
            route_runtime="retained GPT-4.1-mini subjects",
            temperature="not_recorded_in_compact_scorecard",
            token_limit="not_recorded_in_compact_scorecard",
            cache_replay_mode="retained no-call summary",
            prompt_program="direct_labeler_v0_5; evidence_v0_6; evidence_v0_7",
            row_inspection_rule="validation permitted; test aggregate only",
            locked_row_controls="no test row analysis",
            independent_clinical_review="not_completed",
            reproducibility_command="python scripts/check_retained_evidence_manifest.py",
            pooling_unit="prompt_condition",
            unique_rows=None,
            model_row_count=None,
        ),
        make_record(
            artifact_index=inputs.artifact_index,
            task="gan2026",
            criterion_id="robustness_stability",
            measurement_id="gan2026_repeated_temperature_semantic_entropy",
            model_scope=["one retained Gan model subject"],
            split="preflight150",
            row_scope="development_rows_permitted",
            denominator=int(inputs.gan_consistency[0]),
            denominator_status="defined_preflight_rows",
            unit="label_entropy",
            score_stage="final",
            scorer="Gan semantic label entropy across temperatures 0.3, 0.5, 0.7, 1.0",
            repair_policy="retained P2.1 policy",
            value={
                "mean_label_entropy": inputs.gan_consistency[2],
                "residual_label_entropy": inputs.gan_consistency[3],
                "residual_rows": int(inputs.gan_consistency[1]),
            },
            evidence_state="development_answer",
            comparability="construct_only",
            source_artifacts=[inputs.gan_master_path],
            claim_boundary=(
                "One-model repeated-temperature result; raw prose varies while named "
                "semantic decisions are stable."
            ),
            route_runtime="one retained Gan model subject",
            temperature=[0.3, 0.5, 0.7, 1.0],
            token_limit="not_recorded_in_compact_scorecard",
            cache_replay_mode="retained no-call summary",
            prompt_program="P2.1 semantic entropy",
            row_inspection_rule="development preflight rows permitted",
            locked_row_controls="no locked rows used",
            independent_clinical_review="not_completed",
            reproducibility_command="python scripts/check_retained_evidence_manifest.py",
            pooling_unit="letter_temperature_panel",
            unique_rows=int(inputs.gan_consistency[0]),
            model_row_count=int(inputs.gan_consistency[0]) * 4,
        ),
        make_record(
            artifact_index=inputs.artifact_index,
            task="gan2026",
            criterion_id="component_attribution_correction_safety",
            measurement_id="gan2026_validation750_normalization_component_delta",
            model_scope=["saved-output Gan validation subject"],
            split="dev750",
            row_scope="development_rows_permitted",
            denominator=750,
            denominator_status="defined_letters",
            unit="Purist_accuracy_delta",
            score_stage="normalized",
            scorer="Gan Purist accuracy",
            repair_policy="normalization/shared dictionary ablation",
            value=inputs.component_summary["normalization_delta_gan2026"],
            evidence_state="development_answer",
            comparability="construct_only",
            source_artifacts=[inputs.component_path],
            claim_boundary=(
                "Saved-output development ablation; score-inert evidence checks are not "
                "proved unnecessary."
            ),
            route_runtime="no-call saved-output replay",
            temperature="not_applicable_no_call_replay",
            token_limit="not_applicable_no_call_replay",
            cache_replay_mode="saved-output no-call replay",
            prompt_program="retained component ablation",
            row_inspection_rule="dev750 rows permitted",
            locked_row_controls="no locked rows used",
            independent_clinical_review="not_completed",
            reproducibility_command="python scripts/cross_task_shared_component_ablation.py",
            pooling_unit="letter",
            unique_rows=750,
            model_row_count=750,
        ),
        make_record(
            artifact_index=inputs.artifact_index,
            task="gan2026",
            criterion_id="coverage_clinical_slice_behavior",
            measurement_id="gan2026_seizure_band_error_variation",
            model_scope=["openai/gpt-4.1-mini v0_reference subject"],
            split="dev750",
            row_scope="development_rows_permitted",
            denominator=750,
            denominator_status="defined_subject_rows",
            unit="error_spread_and_coefficient_of_variation",
            score_stage="final",
            scorer="Gan seizure-band error parity transform",
            repair_policy="retained v0_reference policy",
            value={
                "error_spread": inputs.gan_coverage[0] / 100,
                "coefficient_of_variation": inputs.gan_coverage[1],
                "worst_slice": "seizure_free_duration",
            },
            evidence_state="development_answer",
            comparability="construct_only",
            source_artifacts=[inputs.gan_master_path],
            claim_boundary="Clinical seizure-band variation only; not demographic fairness.",
            route_runtime="openai/gpt-4.1-mini retained subject",
            temperature="not_recorded_in_compact_scorecard",
            token_limit="not_recorded_in_compact_scorecard",
            cache_replay_mode="retained no-call summary",
            prompt_program="v0_reference",
            row_inspection_rule="dev750 rows permitted",
            locked_row_controls="no locked rows used",
            independent_clinical_review="not_completed",
            reproducibility_command="python scripts/check_retained_evidence_manifest.py",
            pooling_unit="clinical_slice",
            unique_rows=750,
            model_row_count=750,
        ),
        make_record(
            artifact_index=inputs.artifact_index,
            task="gan2026",
            criterion_id="coverage_clinical_slice_behavior",
            measurement_id="gan2026_demographic_fairness",
            model_scope=["not_applicable_current_data"],
            split="not_measured",
            row_scope="synthetic_fixture",
            denominator=None,
            denominator_status="not_measured",
            unit="fairness_measure",
            score_stage="final",
            scorer="not_defined",
            repair_policy="not_applicable",
            value=None,
            evidence_state="not_measured",
            comparability="not_comparable",
            source_artifacts=[inputs.gan_master_path],
            claim_boundary="No demographic fairness claim.",
            route_runtime="not_applicable",
            temperature="not_applicable",
            token_limit="not_applicable",
            cache_replay_mode="not_applicable",
            prompt_program="not_applicable",
            row_inspection_rule="no demographic substrate",
            locked_row_controls="test450 remains sealed",
            independent_clinical_review="not_started",
            reproducibility_command="python scripts/check_retained_evidence_manifest.py",
            pooling_unit="not_applicable",
            unique_rows=None,
            model_row_count=None,
            result_state="not_measured",
            not_measured_reason=(
                "Suitable demographic attributes, sample sizes, and a clinically "
                "meaningful fairness question are absent."
            ),
        ),
        make_record(
            artifact_index=inputs.artifact_index,
            task="gan2026",
            criterion_id="operational_reliability",
            measurement_id="gan2026_historical_operational_summary",
            model_scope=["retained Gan reliability subjects"],
            split="dev750+test450",
            row_scope="aggregate_only_rows_sealed",
            denominator=int(inputs.gan_operations[2]),
            denominator_status="defined_processed_rows",
            unit="failures_repairs_and_bounded_cost",
            score_stage="final",
            scorer="operational event accounting",
            repair_policy="retained Gan repair stack",
            value={
                "model_render_failures": int(inputs.gan_operations[0]),
                "recoverable_repairs": int(inputs.gan_operations[1]),
                "offline_estimated_usd_per_1000_notes": inputs.gan_operations[3],
            },
            evidence_state="diagnostic",
            comparability="construct_only",
            source_artifacts=[inputs.gan_master_path],
            claim_boundary=(
                "Historical aggregate operations and bounded offline estimate; matched "
                "latency and retry telemetry unavailable."
            ),
            route_runtime="mixed retained Gan subjects",
            temperature="mixed retained conditions",
            token_limit="not_recorded_in_compact_scorecard",
            cache_replay_mode="retained no-call summary",
            prompt_program="mixed retained Gan subjects",
            row_inspection_rule="validation permitted; test aggregate only",
            locked_row_controls="test450 rows sealed",
            independent_clinical_review="not_applicable_operational_measure",
            reproducibility_command="python scripts/check_retained_evidence_manifest.py",
            pooling_unit="processed_row",
            unique_rows=int(inputs.gan_operations[2]),
            model_row_count=int(inputs.gan_operations[2]),
        ),
        make_record(
            **inputs.common_gan,
            criterion_id="operational_reliability",
            measurement_id="gan2026_six_model_test450_operational_events",
            model_scope=SIX_MODELS,
            split="test450",
            row_scope="aggregate_only_rows_sealed",
            denominator=450,
            denominator_status="defined_per_model_letters",
            unit="event_counts",
            score_stage="final",
            scorer="aggregate run event accounting",
            repair_policy="hybrid_full_stack",
            value=inputs.gan_ops,
            evidence_state="aggregate_holdout_evidence",
            comparability="construct_only",
            source_artifacts=[inputs.hosted_path],
            claim_boundary=(
                "Observed aggregate events for six unmatched provider/runtime conditions; "
                "no efficiency ranking."
            ),
            prompt_program="gan2026_hybrid_structured_events_v0.5",
            reproducibility_command="python scripts/check_retained_evidence_manifest.py",
            unique_rows=450,
            model_row_count=2700,
        ),
    ]
