"use client";
import { useState } from "react";
import { ArrowRight, Download, Info, Users } from "lucide-react";
import { syntheticPatients, stateFor, visitMonths, type SyntheticPatient, type Visit } from "@/lib/syntheticPatients";
import s from "./story.module.css";
import base from "./demo.module.css";
import ApplicationIcon from "./ApplicationIcon";
import CohortIntroduction from "./CohortIntroduction";
import LongitudinalIntroduction from "./LongitudinalIntroduction";
import PredictionIntroduction from "./PredictionIntroduction";
import EmergencyRiskExplorer from "./EmergencyRiskExplorer";

type Mode = "cohort" | "longitudinal" | "prediction";
function Evidence({ patient, visit }: { patient: SyntheticPatient; visit: Visit }) {
  return <aside className={s.evidencePanel} aria-label="Simulated source note"><span className={s.kicker}>Trace to the source</span><h2>{patient.id} <span>· Month {visit.month}</span></h2><div className={s.recordValue}><small>Authored frequency record</small><strong>{stateFor(visit.rate)}</strong><span>{visit.rate === null ? "Unknown is not zero" : visit.rate === 0 ? "Explicit seizure freedom" : `${visit.rate} seizures per month`}</span></div><blockquote>{visit.evidence}</blockquote><details className={s.more}><summary>Read the full simulated note</summary><pre>{visit.note}</pre></details><p className={s.finePrint}>Fictional note and record.</p></aside>;
}
function downloadPatients(patients: SyntheticPatient[]) {
  const blob = new Blob([JSON.stringify({ kind: "fictional-interface-demonstration", version: 1, seed: 8056, provenance: "Notes and records co-generated, not model-extracted. No real patients or benchmark rows.", patients }, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob), a = document.createElement("a");
  a.href = url; a.download = "synthetic-cohort.json"; a.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}
export default function Applications({ onBatch }: { onBatch: () => void }) {
  const [predictionExplorer, setPredictionExplorer] = useState(false);
  const [longitudinalExplorer, setLongitudinalExplorer] = useState(false);
  const [cohortExplorer, setCohortExplorer] = useState(false);
  const [mode, setMode] = useState<Mode>("cohort");
  const [epilepsy, setEpilepsy] = useState("All");
  const [frequency, setFrequency] = useState("All");
  const [month, setMonth] = useState(6);
  const [patientId, setPatientId] = useState("S001");
  const [visitMonth, setVisitMonth] = useState(6);
  const patients = syntheticPatients.filter(p => (epilepsy === "All" || p.type === epilepsy) && (frequency === "All" || stateFor(p.visits.find(v => v.month === month)!.rate) === frequency));
  const active = patients.find(p => p.id === patientId) ?? patients[0];
  const inspected = active;
  const visit = inspected?.visits.find(v => v.month === (mode === "cohort" ? month : visitMonth)) ?? inspected?.visits[0];
  function selectVisit(p: SyntheticPatient, v: Visit) { setPatientId(p.id); setVisitMonth(v.month); }
  function resetFilters() { setEpilepsy("All"); setFrequency("All"); setMonth(6); }
  return <div className={s.chapter}>
    <nav className={s.resultTabs} aria-label="Application demonstrations">{([{ id: "cohort", label: "Clinical trials & cohorts" }, { id: "longitudinal", label: "Patient timelines" }, { id: "prediction", label: "Risk stratification" }] as const).map(m => <button key={m.id} aria-pressed={mode === m.id} onClick={() => { setMode(m.id); if (m.id === "prediction") setVisitMonth(6); }}><ApplicationIcon kind={m.id} />{m.label}</button>)}</nav>
    {mode === "cohort" && !cohortExplorer && <CohortIntroduction onExplore={preset => { if (preset) { setEpilepsy("Focal"); setFrequency("4+ / month"); setMonth(6); setPatientId("S008"); } else resetFilters(); setCohortExplorer(true); }} />}
    {mode === "cohort" && cohortExplorer && <div className={s.sectionHeading}><div><h1>Screen candidate cohort</h1><p>Apply search criteria, review highlighted quotes, and export matching records.</p></div><button className={base.secondary} onClick={() => setCohortExplorer(false)}>Back to overview</button></div>}
    {mode === "longitudinal" && !longitudinalExplorer && <LongitudinalIntroduction onExplore={() => { resetFilters(); setVisitMonth(6); setLongitudinalExplorer(true); }} />}
    {mode === "longitudinal" && longitudinalExplorer && <div className={s.sectionHeading}><div><h1>12-Month Seizure Timelines</h1><p>Track the same patient cohort across 5 clinic visits.</p></div><button className={base.secondary} onClick={() => setLongitudinalExplorer(false)}>Back to overview</button></div>}
    {((mode === "longitudinal" && longitudinalExplorer) || (mode === "cohort" && cohortExplorer)) && <div className={s.filters} aria-label="Cohort filters"><label>Epilepsy type<select value={epilepsy} onChange={e => setEpilepsy(e.target.value)}><option>All</option><option>Focal</option><option>Generalised</option></select></label><label>Seizure frequency<select value={frequency} onChange={e => setFrequency(e.target.value)}>{["All", "Seizure free", "1–3 / month", "4+ / month", "Unknown"].map(v => <option key={v}>{v}</option>)}</select></label><label>Clinic visit<select value={month} onChange={e => setMonth(Number(e.target.value))}>{visitMonths.map(m => <option key={m} value={m}>Month {m}</option>)}</select></label><button className={base.secondary} onClick={resetFilters}>Reset filters</button><button className={base.secondary} disabled={!patients.length} onClick={() => downloadPatients(patients)}><Download size={14} />Export cohort (JSON)</button></div>}
    {mode === "cohort" && cohortExplorer && <><div className={s.cohortSummary}><strong aria-live="polite">{patients.length}<small> / 72 patients</small></strong><p>Meet the selected criteria at month {month}. Select any patient to inspect the source note.</p></div><div className={s.applicationGrid}><section className={s.patientArea} aria-label="Matching patient records">{!patients.length ? <div className={s.empty}><h2>No patients match.</h2><p>Try a different visit or broaden your frequency filter.</p><button className={base.secondary} onClick={resetFilters}>Show all patients</button></div> : <div className={s.patientGrid}>{patients.map(p => <button key={p.id} onClick={() => selectVisit(p, p.visits.find(v => v.month === month)!)} aria-pressed={active?.id === p.id}><Users size={18} /><strong>{p.id}</strong><small>{p.type} · {p.age} years</small><span data-state={stateFor(p.visits.find(v => v.month === month)!.rate)}>{stateFor(p.visits.find(v => v.month === month)!.rate)}</span></button>)}</div>}</section>{inspected && visit && <Evidence patient={inspected} visit={visit} />}</div></>}
    {mode === "longitudinal" && longitudinalExplorer && <><div className={s.sectionHeading}><div><h2>Continuous timelines, not isolated snapshots</h2><p>{patients.length} patients filtered at month {month}; follow their progress across all clinic visits.</p></div></div><div className={s.stateLegend}>{["Seizure free", "1–3 / month", "4+ / month", "Unknown"].map(state => <span key={state}><i data-state={state} />{state}</span>)}</div><div className={s.populationChart} aria-label="Recorded states over time for the selected cohort">{visitMonths.map(m => <div key={m}><div className={s.stackedColumn}>{["Unknown", "4+ / month", "1–3 / month", "Seizure free"].map(state => { const n = patients.filter(p => stateFor(p.visits.find(v => v.month === m)!.rate) === state).length; return n > 0 && <span key={state} data-state={state} style={{ height: `${n / patients.length * 100}%` }} title={`${state}: ${n} of ${patients.length}`} aria-label={`${state}: ${n} of ${patients.length}`}>{n}</span>; })}</div><span>Month {m}</span></div>)}</div><div className={s.applicationGrid}><div className={s.timelineWrap}><table className={s.timeline}><caption>Click any visit box to read the clinical letter. Blank entries indicate unmentioned frequency.</caption><thead><tr><th>Patient</th>{visitMonths.map(m => <th key={m}>Month {m}</th>)}</tr></thead><tbody>{patients.map(p => <tr key={p.id}><th>{p.id}</th>{p.visits.map(v => <td key={v.id}><button data-state={stateFor(v.rate)} aria-pressed={active?.id === p.id && visitMonth === v.month} aria-label={`${p.id}, month ${v.month}: ${stateFor(v.rate)}`} onClick={() => selectVisit(p, v)}>{v.rate === null ? "?" : v.rate === 0 ? "Free" : v.rate}</button></td>)}</tr>)}</tbody></table>{!patients.length && <div className={s.empty}><p>No patients match these filters.</p><button className={base.secondary} onClick={resetFilters}>Reset filters</button></div>}</div>{inspected && visit && <Evidence patient={inspected} visit={visit} />}</div><p className={s.finePrint}>Recorded states at each visit · simulated cohort.</p></>}
    {mode === "prediction" && !predictionExplorer && <PredictionIntroduction onExplore={() => setPredictionExplorer(true)} />}
    {mode === "prediction" && predictionExplorer && <EmergencyRiskExplorer onBack={() => setPredictionExplorer(false)} />}
    {((mode === "cohort" && cohortExplorer) || (mode === "longitudinal" && longitudinalExplorer)) && <details className={s.more}><summary><Info size={15} />Where these use cases come from</summary><div><p><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC3540531/" target="_blank" rel="noreferrer">EpiDEA (Cui et al.)</a> uses structured epilepsy information for visual cohort queries. Chang et al. (2026 preprint) build longitudinal epilepsy and seizure-type phenotypes. Xie et al. (2023), <a href="https://doi.org/10.1111/epi.17633" target="_blank" rel="noreferrer">Long-term epilepsy outcome dynamics</a>, link extracted outcomes across visits. <a href="https://doi.org/10.64898/2025.12.01.25341355" target="_blank" rel="noreferrer">CLINES (Yang et al., 2025 preprint)</a> structures clinical narratives; <a href="https://arxiv.org/abs/2508.01956" target="_blank" rel="noreferrer">SNOW (Wang et al., 2025 preprint)</a> generates features for downstream prediction.</p><p>These demonstrations are inspired by those use cases, not replications. The patients, trajectories, notes, and records here are authored simulations with arbitrary distributions. No model extraction was run on them. The dissertation evaluates seizure-frequency extraction; the epilepsy type, medication and longitudinal fields shown here are application mock data.</p></div></details>}
    <div className={s.chapterEnd}><p>Inspect actual saved extraction outputs from the development set.</p><button className={base.secondary} onClick={onBatch}>Open the batch explorer <ArrowRight size={16} /></button></div>
  </div>;
}
