"use client";
import { useMemo, useState } from "react";
import { ArrowRight, Download, Info, Users } from "lucide-react";
import { syntheticPatients, stateFor, visitMonths, fitSyntheticModel, confusionFor, type SyntheticPatient, type Visit } from "@/lib/syntheticPatients";
import s from "./story.module.css";
import base from "./demo.module.css";
import ApplicationIcon from "./ApplicationIcon";
import CohortIntroduction from "./CohortIntroduction";
import LongitudinalIntroduction from "./LongitudinalIntroduction";
import PredictionIntroduction from "./PredictionIntroduction";

type Mode = "cohort" | "longitudinal" | "prediction";
function Evidence({ patient, visit }: { patient: SyntheticPatient; visit: Visit }) {
  return <aside className={s.evidencePanel} aria-label="Simulated source note"><span className={s.kicker}>Trace to the source</span><h2>{patient.id} <span>· Month {visit.month}</span></h2><div className={s.recordValue}><small>Authored frequency record</small><strong>{stateFor(visit.rate)}</strong><span>{visit.rate === null ? "Unknown is not zero" : visit.rate === 0 ? "Explicit seizure freedom" : `${visit.rate} seizures per month`}</span></div><blockquote>{visit.evidence}</blockquote><details className={s.more}><summary>Read the full simulated note</summary><pre>{visit.note}</pre></details><p className={s.finePrint}>Fictional note and record.</p></aside>;
}
function downloadPatients(patients: SyntheticPatient[]) {
  const blob = new Blob([JSON.stringify({ kind: "fictional-interface-demonstration", version: 1, seed: 8056, provenance: "Notes and records co-generated, not model-extracted. No real patients or benchmark rows.", patients }, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob), a = document.createElement("a");
  a.href = url; a.download = "synthetic-cohort.json"; a.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}
export default function Applications({ onBatch }: { onBatch: () => void }) {
  const [predictionExplorer, setPredictionExplorer] = useState(false);
  const [longitudinalExplorer, setLongitudinalExplorer] = useState(false);
  const [cohortExplorer, setCohortExplorer] = useState(false);
  const [mode, setMode] = useState<Mode>("cohort");
  const [epilepsy, setEpilepsy] = useState("All");
  const [frequency, setFrequency] = useState("All");
  const [month, setMonth] = useState(6);
  const [patientId, setPatientId] = useState("S001");
  const [visitMonth, setVisitMonth] = useState(6);
  const [includeNotes, setIncludeNotes] = useState(true);
  const [threshold, setThreshold] = useState(.5);
  const patients = syntheticPatients.filter(p => (epilepsy === "All" || p.type === epilepsy) && (frequency === "All" || stateFor(p.visits.find(v => v.month === month)!.rate) === frequency));
  const active = patients.find(p => p.id === patientId) ?? patients[0];
  const models = useMemo(() => ({ structured: fitSyntheticModel(false), notes: fitSyntheticModel(true) }), []);
  const model = includeNotes ? models.notes : models.structured;
  const confusion = confusionFor(model.rows, threshold);
  const rankedRows = [...model.rows].sort((a, b) => b.probability - a.probability);
  const higherRisk = rankedRows.filter(r => r.probability >= threshold);
  const lowerRisk = rankedRows.filter(r => r.probability < threshold);
  const predictionPatient = model.rows.find(r => r.patient.id === patientId)?.patient ?? model.rows[0]?.patient;
  const inspected = mode === "prediction" ? predictionPatient : active;
  const visit = inspected?.visits.find(v => v.month === (mode === "cohort" ? month : visitMonth)) ?? inspected?.visits[0];
  function selectVisit(p: SyntheticPatient, v: Visit) { setPatientId(p.id); setVisitMonth(v.month); }
  function resetFilters() { setEpilepsy("All"); setFrequency("All"); setMonth(6); }
  return <div className={s.chapter}>
    {mode === "prediction" && predictionExplorer && <div className={s.applicationHeading}><div><span className={s.kicker}>From records to research</span><h1>One patient. Many letters.<br />New questions.</h1><p>Find a cohort, follow its course, or build features for a predictive model.</p></div><div className={s.syntheticBadge}><strong>Entirely synthetic</strong><span>72 fictional patients · 360 visits</span><small>Interactive possibilities, not study findings</small></div></div>}
    <nav className={s.resultTabs} aria-label="Application demonstrations">{([{ id: "cohort", label: "Find a cohort" }, { id: "longitudinal", label: "Follow over time" }, { id: "prediction", label: "Build a prediction" }] as const).map(m => <button key={m.id} aria-pressed={mode === m.id} onClick={() => { setMode(m.id); if (m.id === "prediction") setVisitMonth(6); }}><ApplicationIcon kind={m.id} />{m.label}</button>)}</nav>
    {mode === "cohort" && !cohortExplorer && <CohortIntroduction onExplore={preset => { if (preset) { setEpilepsy("Focal"); setFrequency("4+ / month"); setMonth(6); } else resetFilters(); setCohortExplorer(true); }} />}
    {mode === "cohort" && cohortExplorer && <div className={s.sectionHeading}><div><h1>Inspect a candidate cohort.</h1><p>Filter patients. Check the notes. Export candidates.</p></div><button className={base.secondary} onClick={() => setCohortExplorer(false)}>Back to the workflow</button></div>}
    {mode === "longitudinal" && !longitudinalExplorer && <LongitudinalIntroduction onExplore={() => { resetFilters(); setVisitMonth(6); setLongitudinalExplorer(true); }} />}
    {mode === "longitudinal" && longitudinalExplorer && <div className={s.sectionHeading}><div><h1>Inspect the visit histories.</h1><p>Same patients. Five visits.</p></div><button className={base.secondary} onClick={() => setLongitudinalExplorer(false)}>Back to the workflow</button></div>}
    {((mode === "longitudinal" && longitudinalExplorer) || (mode === "cohort" && cohortExplorer)) && <div className={s.filters} aria-label="Synthetic cohort filters"><label>Epilepsy type<select value={epilepsy} onChange={e => setEpilepsy(e.target.value)}><option>All</option><option>Focal</option><option>Generalised</option></select></label><label>Recorded frequency<select value={frequency} onChange={e => setFrequency(e.target.value)}>{["All", "Seizure free", "1–3 / month", "4+ / month", "Unknown"].map(v => <option key={v}>{v}</option>)}</select></label><label>At visit<select value={month} onChange={e => setMonth(Number(e.target.value))}>{visitMonths.map(m => <option key={m} value={m}>Month {m}</option>)}</select></label><button className={base.secondary} onClick={resetFilters}>Reset</button><button className={base.secondary} disabled={!patients.length} onClick={() => downloadPatients(patients)}><Download size={14} />Export cohort</button></div>}
    {mode === "cohort" && cohortExplorer && <><div className={s.cohortSummary}><strong aria-live="polite">{patients.length}<small> / 72 patients</small></strong><p>Meet the selected record filters at month {month}. Select a patient to inspect the evidence.</p></div><div className={s.applicationGrid}><section className={s.patientArea} aria-label="Matching fictional patients">{!patients.length ? <div className={s.empty}><h2>No patients match.</h2><p>Try a different visit or broaden the frequency filter.</p><button className={base.secondary} onClick={resetFilters}>Show all patients</button></div> : <div className={s.patientGrid}>{patients.map(p => <button key={p.id} onClick={() => selectVisit(p, p.visits.find(v => v.month === month)!)} aria-pressed={active?.id === p.id}><Users size={18} /><strong>{p.id}</strong><small>{p.type} · {p.age} years</small><span data-state={stateFor(p.visits.find(v => v.month === month)!.rate)}>{stateFor(p.visits.find(v => v.month === month)!.rate)}</span></button>)}</div>}</section>{inspected && visit && <Evidence patient={inspected} visit={visit} />}</div></>}
    {mode === "longitudinal" && longitudinalExplorer && <><div className={s.sectionHeading}><div><h2>A course, not a single label.</h2><p>{patients.length} patients selected at month {month}; follow those same patients at every visit.</p></div></div><div className={s.stateLegend}>{["Seizure free", "1–3 / month", "4+ / month", "Unknown"].map(state => <span key={state}><i data-state={state} />{state}</span>)}</div><div className={s.populationChart} aria-label="Recorded states over time for the selected cohort">{visitMonths.map(m => <div key={m}><div className={s.stackedColumn}>{["Unknown", "4+ / month", "1–3 / month", "Seizure free"].map(state => { const n = patients.filter(p => stateFor(p.visits.find(v => v.month === m)!.rate) === state).length; return n > 0 && <span key={state} data-state={state} style={{ height: `${n / patients.length * 100}%` }} title={`${state}: ${n} of ${patients.length}`} aria-label={`${state}: ${n} of ${patients.length}`}>{n}</span>; })}</div><span>Month {m}</span></div>)}</div><div className={s.applicationGrid}><div className={s.timelineWrap}><table className={s.timeline}><caption>Select any visit to read its source note. Blank frequency stays unknown.</caption><thead><tr><th>Patient</th>{visitMonths.map(m => <th key={m}>Month {m}</th>)}</tr></thead><tbody>{patients.map(p => <tr key={p.id}><th>{p.id}</th>{p.visits.map(v => <td key={v.id}><button data-state={stateFor(v.rate)} aria-pressed={active?.id === p.id && visitMonth === v.month} aria-label={`${p.id}, month ${v.month}: ${stateFor(v.rate)}`} onClick={() => selectVisit(p, v)}>{v.rate === null ? "?" : v.rate === 0 ? "Free" : v.rate}</button></td>)}</tr>)}</tbody></table>{!patients.length && <div className={s.empty}><p>No patients match these filters.</p><button className={base.secondary} onClick={resetFilters}>Reset filters</button></div>}</div>{inspected && visit && <Evidence patient={inspected} visit={visit} />}</div><p className={s.finePrint}>Recorded states at each visit · fictional cohort.</p></>}
    {mode === "prediction" && !predictionExplorer && <PredictionIntroduction onExplore={() => { setIncludeNotes(true); setThreshold(.5); setVisitMonth(6); setPredictionExplorer(true); }} />}
    {mode === "prediction" && predictionExplorer && <>
      <button className={base.secondary} onClick={() => setPredictionExplorer(false)}>Back to the workflow</button>
      <div className={s.predictionIntro}><h2>Turn patient histories into risk groups.</h2><p>Rank patients by modelled risk, choose a cutoff, and inspect the evidence behind each score.</p></div>
      <div className={s.predictionFlow}><span>Visits 0–6<small>Features only</small></span><ArrowRight size={20} /><span>{model.train.length} training patients<small>Fit + standardise here</small></span><ArrowRight size={20} /><span>{model.test.length} test patients<small>Estimate risk</small></span></div>
      <div className={s.featureSwitch}><div><h3>Add the information inside the notes.</h3><p>Age + medication count{includeNotes ? " + recent frequency, change, and missingness" : " only"}</p></div><button className={base.secondary} aria-pressed={includeNotes} onClick={() => setIncludeNotes(!includeNotes)}>{includeNotes ? "Note features on" : "Note features off"}</button></div>
      <div className={s.predictionMetrics}><div><small>Structured fields only · test AUC</small><strong>{models.structured.auc?.toFixed(2) ?? "Undefined"}</strong></div><div data-emphasised={includeNotes}><small>With note features · test AUC</small><strong>{models.notes.auc?.toFixed(2) ?? "Undefined"}</strong></div><p>Toy-model results · fictional data.</p></div>
      <div className={s.applicationGrid}><section><div className={s.threshold}><label htmlFor="prediction-threshold">Risk-group cutoff <strong>{Math.round(threshold * 100)}%</strong></label><input id="prediction-threshold" type="range" min="5" max="95" step="5" value={threshold * 100} onChange={e => setThreshold(Number(e.target.value) / 100)} /><p>Move the cutoff to change who falls into each risk group.</p></div><div className={s.riskGroups} aria-live="polite"><div><span>Higher modelled risk</span><strong>{higherRisk.length}</strong><small>Score ≥ {Math.round(threshold * 100)}%</small></div><div><span>Lower modelled risk</span><strong>{lowerRisk.length}</strong><small>Score &lt; {Math.round(threshold * 100)}%</small></div></div><div className={s.predictionRows}><h3>Risk scores · highest first</h3>{rankedRows.map(r => <button key={r.patient.id} aria-pressed={predictionPatient?.id === r.patient.id} onClick={() => { setPatientId(r.patient.id); setVisitMonth(6); }}><strong>{r.patient.id}</strong><span className={s.probabilityTrack}><i style={{ width: `${r.probability * 100}%` }} /></span><span>{Math.round(r.probability * 100)}%</span><small>{r.probability >= threshold ? "Higher risk" : "Lower risk"}</small></button>)}</div></section>{inspected && visit && <div><Evidence patient={inspected} visit={visit} /><div className={s.visitChooser}><span>Inspect feature visits</span>{[0, 3, 6].map(m => <button key={m} aria-pressed={visitMonth === m} onClick={() => setVisitMonth(m)}>Month {m}</button>)}</div></div>}</div>
      <details className={s.more}><summary><Info size={15} />Model recipe and limitations</summary><div><p>The illustrative risk score estimates the probability of any seizure documented at month 12, using records through month 6. It does not estimate a monthly frequency. The cutoff defines demonstration risk groups, not a clinical action threshold.</p><p>At this cutoff: {confusion.tp} true positives, {confusion.fp} false positives, {confusion.fn} missed outcomes and {confusion.tn} true negatives.</p><p>Deterministic generator v1, seed 8056. Patient index modulo 3 assigns test patients before outcomes are considered. {model.excluded} patients with unknown month-12 frequency are excluded from both models. Cohort filters do not change the prediction experiment. Standardisation is fitted on training patients only. Logistic regression uses 700 gradient steps, learning rate 0.08 and L2 penalty 0.04; the intercept is unpenalised.</p><p>Note features: last known monthly frequency by month 6 (zero fallback if all are missing), change from first to last known frequency, and number of missing-frequency visits through month 6. Missingness is retained as a feature. The outcome comes from a future visit and is never an input. AUC gives ties half credit; it is undefined for a single-class test sample. No clinical model has been trained or validated.</p></div></details>
    </>}
    {((mode === "prediction" && predictionExplorer) || (mode === "cohort" && cohortExplorer) || (mode === "longitudinal" && longitudinalExplorer)) && <details className={s.more}><summary><Info size={15} />Where these use cases come from</summary><div><p><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC3540531/" target="_blank" rel="noreferrer">EpiDEA (Cui et al.)</a> uses structured epilepsy information for visual cohort queries. Chang et al. (2026 preprint) build longitudinal epilepsy and seizure-type phenotypes. Xie et al. (2023), <a href="https://doi.org/10.1111/epi.17633" target="_blank" rel="noreferrer">Long-term epilepsy outcome dynamics</a>, link extracted outcomes across visits. <a href="https://doi.org/10.64898/2025.12.01.25341355" target="_blank" rel="noreferrer">CLINES (Yang et al., 2025 preprint)</a> structures clinical narratives; <a href="https://arxiv.org/abs/2508.01956" target="_blank" rel="noreferrer">SNOW (Wang et al., 2025 preprint)</a> generates features for downstream prediction.</p><p>These demonstrations are inspired by those use cases, not replications. The patients, trajectories, notes, and records here are authored simulations with arbitrary distributions. No model extraction was run on them. The dissertation evaluates seizure-frequency extraction; the epilepsy type, medication and longitudinal fields shown here are application mock data.</p></div></details>}
    <div className={s.chapterEnd}><p>Inspect actual saved extraction outputs from the development set.</p><button className={base.secondary} onClick={onBatch}>Open the existing batch explorer <ArrowRight size={16} /></button></div>
  </div>;
}
