import ApplicationIcon from "./ApplicationIcon";
import Image from "next/image";
import { ArrowRight, Check, Search } from "lucide-react";
import { syntheticPatients } from "@/lib/syntheticPatients";
import s from "./applicationStories.module.css";
const focal = syntheticPatients.filter(p => p.type === "Focal");
const matches = focal.filter(p => { const rate = p.visits.find(v => v.month === 6)!.rate; return rate !== null && rate >= 4; });
const unknown = focal.filter(p => p.visits.find(v => v.month === 6)!.rate === null);
const example = matches.find(p => p.id === "S008") ?? matches[0];
const visit = example.visits.find(v => v.month === 6)!;
export default function CohortIntroduction({ onExplore }: { onExplore: (preset: boolean) => void }) {
  return <div className={s.story}>
    <section className={s.hero}><div><span className={s.badge}><ApplicationIcon kind="cohort" />Clinical trials &amp; cohorts · simulated data</span><h1>Find the right patients<br />for a clinical study.</h1><p>Filter clinical notes by disease type and seizure frequency, then verify candidates against original text.</p><button className={s.action} onClick={() => onExplore(true)}>Screen candidate cohort <ArrowRight size={17} /></button></div><Image className={s.heroIllustration} src="/demo/imagery/cohort-hero-v2.png" alt="Paper sculpture of a researcher reviewing patient evidence and gathering a smaller set of candidate records." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 55vw" /></section>
    <section className={`${s.section} ${s.split} ${s.splitReverse}`}><div><h2>Set your inclusion criteria.</h2><p>Define the target patient population and relevant time window.</p><ul className={s.cohortCriteria}><li>Focal epilepsy</li><li>4+ seizures / month</li><li>Month 6 visit</li></ul></div><Image className={s.heroIllustration} src="/demo/imagery/cohort-criteria-v2.png" alt="Paper patient records sorted into teal, sage and ochre trays beside a criteria checklist." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 55vw" /></section>
    <section className={`${s.section} ${s.split}`}><div><h2>Verify matches<br />against the original note.</h2><p>Every extracted match preserves its supporting clinical quote.</p><div className={s.cohortEvidence}><span>{example.id} · focal epilepsy · month 6</span><q>{visit.evidence}</q><strong>{visit.rate} / month → meets the study threshold</strong></div></div><Image className={s.heroIllustration} src="/demo/imagery/cohort-evidence-v2.png" alt="Two evidence citations in a patient folder linked to their highlighted passages in the source letter." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 55vw" /></section>
    <section className={`${s.section} ${s.split} ${s.splitReverse}`}><div><h2>{matches.length} matching candidates.<br />{unknown.length} require manual review.</h2><p>Select any patient, review their clinic note, and export the cohort.</p><button className={s.action} onClick={() => onExplore(true)}><Search size={16} />Review matching patients</button></div><div className={s.roster} aria-label="Example candidate list">{matches.slice(0, 3).map(p => <div key={p.id}><Image className={s.candidateIcon} src="/demo/imagery/candidate-record-v2.png" alt="" width={44} height={44} sizes="44px" /><strong>{p.id}</strong><span>Focal · {p.visits.find(v => v.month === 6)!.rate} / month</span><Check size={18} /></div>)}<p className={s.caption}>Candidate list · ready for clinical audit</p></div></section>
    <div className={s.footer}><small>72 simulated patient profiles · 360 clinic visits</small><button onClick={() => onExplore(false)}>Choose custom criteria <ArrowRight size={16} /></button></div>
    <details className={s.note}><summary>Methodology notes &amp; sources</summary><p>This example selects patients with focal epilepsy and at least four seizures per month at month 6. Patients with unknown frequency remain flagged for manual review. A filtered search produces a candidate list for clinical audit, not automatic inclusion.</p><p>Simulated records demonstrate filtering, source inspection, and JSON export. Background: literature on clinical cohort identification and trial feasibility screening (EpiDEA, Cui et al.; CLINES, Yang et al.).</p></details>
  </div>;
}
