import { Activity, ArrowRight, CalendarDays, Check, CircleHelp, FileText, Search, UserRound, Users, X } from "lucide-react";
import { syntheticPatients } from "@/lib/syntheticPatients";
import s from "./applicationStories.module.css";
const focal = syntheticPatients.filter(p => p.type === "Focal");
const matches = focal.filter(p => { const rate = p.visits.find(v => v.month === 6)!.rate; return rate !== null && rate >= 4; });
const unknown = focal.filter(p => p.visits.find(v => v.month === 6)!.rate === null);
const example = matches[0];
const visit = example.visits.find(v => v.month === 6)!;
export default function CohortIntroduction({ onExplore }: { onExplore: (preset: boolean) => void }) {
  return <div className={s.story}>
    <section className={s.hero}><div><span className={s.badge}><Users size={15} />Find a cohort · fictional data</span><h1>Find the patients<br />who fit the question.</h1><p>Define the group. Check the evidence. Build the candidate list.</p><button className={s.action} onClick={() => onExplore(true)}>Explore the cohort <ArrowRight size={17} /></button></div><div><div className={s.populationKey}><span><strong>72</strong>patients</span><span><strong>{matches.length}</strong>candidates</span></div><div className={s.people} role="img" aria-label={`72 fictional patients: ${matches.length} match the example criteria; ${unknown.length} focal patients have unknown frequency.`}>{syntheticPatients.map(p => <UserRound key={p.id} aria-hidden="true" data-match={matches.includes(p)} data-unknown={unknown.includes(p)} />)}</div><div className={s.populationKey}><span>Green · matches</span><span>Amber · needs information</span></div></div></section>
    <section className={s.section}><h2>Set the criteria.</h2><div className={s.criteria}><span><Users />Focal epilepsy</span><b>+</b><span><Activity />4+ seizures / month</span><b>+</b><span><CalendarDays />Month 6</span></div></section>
    <section className={`${s.section} ${s.split}`}><div><h2>Follow a match<br />back to the note.</h2><p>Each candidate keeps its supporting evidence.</p><div className={s.routes}><div><Check /><strong>Match</strong><span>Criteria met</span></div><div><CircleHelp /><strong>Review</strong><span>Information missing</span></div><div><X /><strong>Exclude</strong><span>Criteria not met</span></div></div></div><div className={s.evidence}><span><FileText size={16} />{example.id} · focal epilepsy · month 6</span><q>{visit.evidence}</q><strong>{visit.rate} / month → meets the threshold</strong></div></section>
    <section className={`${s.section} ${s.split}`}><div><h2>{matches.length} candidates.<br />{unknown.length} need another look.</h2><p>Open a patient, inspect the note, export the records.</p><button className={s.action} onClick={() => onExplore(true)}><Search size={16} />Inspect the candidates</button></div><div className={s.roster} aria-label="Example candidate list">{matches.slice(0, 3).map(p => <div key={p.id}><UserRound /><strong>{p.id}</strong><span>Focal · {p.visits.find(v => v.month === 6)!.rate} / month</span><Check size={18} /></div>)}<p className={s.caption}>Candidate preview · review comes next</p></div></section>
    <div className={s.footer}><small>72 fictional patients · 360 authored visits</small><button onClick={() => onExplore(false)}>Choose your own criteria <ArrowRight size={16} /></button></div>
    <details className={s.note}><summary>Presenter notes & sources</summary><p>This example defines focal epilepsy and a recorded frequency of at least four seizures per month at month 6. The seven focal patients with unknown frequency remain a separate review group. A filtered list is a candidate list, not adjudicated cohort membership.</p><p>Notes and records were generated together. The explorer demonstrates filtering, source inspection and export; it does not run extraction or record clinical review decisions. Reconciling multiple documents and evaluating missed patients are further workflow steps.</p><p>Background: supplied Cohort Identification Literature Review, 7 September 2026, pp. 3, 7–8. The review distinguishes research cohort construction, trial feasibility and recruitment, and emphasises explicit criteria, evidence and uncertainty.</p></details>
  </div>;
}
