import ApplicationIcon from "./ApplicationIcon";
import Image from "next/image";
import { ArrowRight, Check, Search } from "lucide-react";
import { syntheticPatients } from "@/lib/syntheticPatients";
import s from "./applicationStories.module.css";
const focal = syntheticPatients.filter(p => p.type === "Focal");
const matches = focal.filter(p => { const rate = p.visits.find(v => v.month === 6)!.rate; return rate !== null && rate >= 4; });
const unknown = focal.filter(p => p.visits.find(v => v.month === 6)!.rate === null);
const example = matches[0];
const visit = example.visits.find(v => v.month === 6)!;
export default function CohortIntroduction({ onExplore }: { onExplore: (preset: boolean) => void }) {
  return <div className={s.story}>
    <section className={s.hero}><div><span className={s.badge}><ApplicationIcon kind="cohort" />Find a cohort · fictional data</span><h1>Find the patients<br />who fit the question.</h1><p>Define the group. Check the evidence. Build the candidate list.</p><button className={s.action} onClick={() => onExplore(true)}>Explore the cohort <ArrowRight size={17} /></button></div><Image className={s.heroIllustration} src="/demo/imagery/cohort-hero-v1.png" alt="Paper sculpture of a researcher reviewing patient evidence and gathering a smaller set of candidate records." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 55vw" /></section>
    <section className={`${s.section} ${s.split}`}><div><h2>Set the criteria.</h2><p>Choose who to include and when to look.</p><ul className={s.cohortCriteria}><li>Focal epilepsy</li><li>4+ seizures / month</li><li>Month 6</li></ul></div><Image className={s.heroIllustration} src="/demo/imagery/cohort-criteria-v1.png" alt="Paper patient records sorted into teal, sage and ochre trays beside a criteria checklist." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 55vw" /></section>
    <section className={`${s.section} ${s.split}`}><div><h2>Follow a match<br />back to the note.</h2><p>Each candidate keeps its supporting evidence.</p><div className={s.cohortEvidence}><span>{example.id} · focal epilepsy · month 6</span><q>{visit.evidence}</q><strong>{visit.rate} / month → meets the threshold</strong></div></div><Image className={s.heroIllustration} src="/demo/imagery/cohort-evidence-v1.png" alt="Two evidence citations in a patient folder linked to their highlighted passages in the source letter." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 55vw" /></section>
    <section className={`${s.section} ${s.split}`}><div><h2>{matches.length} candidates.<br />{unknown.length} need another look.</h2><p>Open a patient, inspect the note, export the records.</p><button className={s.action} onClick={() => onExplore(true)}><Search size={16} />Inspect the candidates</button></div><div className={s.roster} aria-label="Example candidate list">{matches.slice(0, 3).map(p => <div key={p.id}><Image className={s.candidateIcon} src="/demo/imagery/candidate-record-v1.png" alt="" width={44} height={44} sizes="44px" /><strong>{p.id}</strong><span>Focal · {p.visits.find(v => v.month === 6)!.rate} / month</span><Check size={18} /></div>)}<p className={s.caption}>Candidate preview · review comes next</p></div></section>
    <div className={s.footer}><small>72 fictional patients · 360 authored visits</small><button onClick={() => onExplore(false)}>Choose your own criteria <ArrowRight size={16} /></button></div>
    <details className={s.note}><summary>Presenter notes & sources</summary><p>This example defines focal epilepsy and a recorded frequency of at least four seizures per month at month 6. The seven focal patients with unknown frequency remain a separate review group. A filtered list is a candidate list, not adjudicated cohort membership.</p><p>Notes and records were generated together. The explorer demonstrates filtering, source inspection and export; it does not run extraction or record clinical review decisions. Reconciling multiple documents and evaluating missed patients are further workflow steps.</p><p>Background: supplied Cohort Identification Literature Review, 7 September 2026, pp. 3, 7–8. The review distinguishes research cohort construction, trial feasibility and recruitment, and emphasises explicit criteria, evidence and uncertainty.</p></details>
  </div>;
}
