import { useState } from "react";
import { Activity, ArrowLeft, ArrowRight, CalendarDays, Copy, FileText, GitMerge, Users } from "lucide-react";
import { syntheticPatients, stateFor, visitMonths } from "@/lib/syntheticPatients";
import s from "./applicationStories.module.css";
const example = syntheticPatients.find(p => p.visits.some(v => v.rate === null) && p.visits.some(v => v.rate !== null))!;
const states = ["Seizure free", "1–3 / month", "4+ / month", "Unknown"];
export default function LongitudinalIntroduction({ onExplore }: { onExplore: () => void }) {
  const [month, setMonth] = useState(6);
  const visit = example.visits.find(v => v.month === month)!;
  return <div className={s.story}>
    <section className={s.hero}><div><span className={s.badge}><Activity size={15} />Follow over time · fictional data</span><h1>Follow a patient.<br />See what changes.</h1><p>Every visit adds to the picture.</p><button className={s.action} onClick={onExplore}>Explore the histories <ArrowRight size={17} /></button></div><div><div className={s.visitStrip} aria-label={`${example.id} visit history`}>{example.visits.map(v => <button key={v.month} aria-pressed={month === v.month} onClick={() => setMonth(v.month)} data-unknown={v.rate === null}><span>Month {v.month}</span><strong>{v.rate === null ? "?" : v.rate === 0 ? "0" : v.rate}</strong><small>{v.rate === null ? "Unknown" : "per month"}</small></button>)}</div><div className={s.sourceQuote}><span>{example.id} · month {month} · select a visit</span><q>{visit.evidence}</q></div></div></section>
    <div className={s.scope}><div><Users /><span><strong>72 patients</strong><small>One fixed group</small></span></div><div><CalendarDays /><span><strong>5 visits</strong><small>Months 0–12</small></span></div><div><Activity /><span><strong>Seizure frequency</strong><small>At each visit</small></span></div></div>
    <section className={`${s.section} ${s.split}`}><div><h2>Put each event<br />in its time.</h2><p>When it happened. When it was recorded.</p><div className={s.timeMap}><div><strong>February</strong><span>Seizure occurred</span></div><ArrowLeft /><div><strong>December</strong><span>Letter written</span></div></div></div><div className={s.evidence}><span><FileText size={16} />December letter · illustrative</span><q>She had a seizure in February.</q><strong>One event, two dates.</strong></div></section>
    <section className={s.section}><h2>Bring the history together.</h2><div className={s.routes}><div><Copy /><strong>Repeated mention</strong><span>Keep one event</span></div><div><GitMerge /><strong>New information</strong><span>Update the history</span></div><div><Activity /><strong>A gap</strong><span>Keep it visible</span></div></div></section>
    <section className={`${s.section} ${s.split}`}><div><h2>From one history<br />to the whole cohort.</h2><p>Compare the same 72 patients at every visit.</p><button className={s.action} onClick={onExplore}>Inspect the timeline <ArrowRight size={17} /></button></div><div><div className={s.chart}>{visitMonths.map(m => <div key={m}><div className={s.stack}>{states.map((state, i) => { const count = syntheticPatients.filter(p => stateFor(p.visits.find(v => v.month === m)!.rate) === state).length; return count > 0 && <span key={state} data-state={i} style={{height: `${count / 72 * 100}%`}} title={`${state}: ${count}`} aria-label={`Month ${m}, ${state}: ${count}`}>{count}</span>; })}</div><small>Month {m}</small></div>)}</div><div className={s.legend}>{states.map((state, i) => <span key={state}><i data-state={i} />{state}</span>)}</div></div></section>
    <div className={s.footer}><small>Fictional visit histories · select a point to inspect its source</small><button onClick={onExplore}>Open the explorer <ArrowRight size={16} /></button></div>
    <details className={s.note}><summary>Presenter notes & sources</summary><p>The displayed outcome is documented frequency at a visit, not continuous seizure freedom or a treatment effect. Unknown visits stay unknown. Notes and records were generated together; no extraction or reconciliation was run on them.</p><p>Event time, documentation time and information availability can differ. A later letter may revise a retrospective history, but cannot supply a prediction made earlier. Repeated mentions need checking before deduplication; conflicts and uncertain dates require review.</p><p>The explorer selects a cohort at one reference visit and follows those same patients across all visits. These summaries are descriptive, not recurrence-risk or survival estimates.</p><p>Background: supplied From clinical letters to longitudinal evidence review, 7 September 2026, pp. 3, 7–8. Its focus is evidence records, reconciled timelines and study-specific analytical tables.</p></details>
  </div>;
}
