import ApplicationIcon from "./ApplicationIcon";
import Image from "next/image";
import { Activity, ArrowRight, CalendarDays, Users } from "lucide-react";
import { syntheticPatients, stateFor, visitMonths } from "@/lib/syntheticPatients";
import s from "./applicationStories.module.css";
const states = ["Seizure free", "1–3 / month", "4+ / month", "Unknown"];
export default function LongitudinalIntroduction({ onExplore }: { onExplore: () => void }) {
  return <div className={s.story}>
    <section className={s.hero}><div><span className={s.badge}><ApplicationIcon kind="longitudinal" />Follow over time · fictional data</span><h1>Follow a patient.<br />See what changes.</h1><p>Every visit adds to the picture.</p><button className={s.action} onClick={onExplore}>Explore the histories <ArrowRight size={17} /></button></div><Image className={s.heroIllustration} src="/demo/imagery/longitudinal-hero-v1.png" alt="Paper sculpture of a researcher reviewing one patient’s history across an unfolding sequence of visit records." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 55vw" /></section>
    <div className={s.scope}><div><Users /><span><strong>72 patients</strong><small>One fixed group</small></span></div><div><CalendarDays /><span><strong>5 visits</strong><small>Months 0–12</small></span></div><div><Activity /><span><strong>Seizure frequency</strong><small>At each visit</small></span></div></div>
    <section className={`${s.section} ${s.split}`}><div><h2>One event.<br />Two dates.</h2><p>Keep when it happened separate from when it was recorded.</p><ul className={s.cohortCriteria}><li>February · seizure occurred</li><li>December · letter written</li></ul></div><Image className={s.heroIllustration} src="/demo/imagery/longitudinal-two-dates-v1.png" alt="A December letter says: She had a seizure in February. Its quotation connects back to a single event on the February calendar." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 55vw" /></section>
    <section className={s.section}><h2>Bring the history together.</h2><div className={s.historyIllustrations}><article><Image className={s.heroIllustration} src="/demo/imagery/history-mentions-v1.png" alt="Two source quotations connect to the same event." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 33vw" /><h3>Repeated mentions</h3><p>Keep one event, with both sources.</p></article><article><Image className={s.heroIllustration} src="/demo/imagery/history-new-evidence-v1.png" alt="A new source quotation joins the existing patient record." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 33vw" /><h3>New information</h3><p>Add evidence to the existing history.</p></article><article><Image className={s.heroIllustration} src="/demo/imagery/history-gap-v1.png" alt="One patient’s unfolding history retains an empty evidence slot between documented visits." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 33vw" /><h3>A gap</h3><p>Keep missing evidence visible.</p></article></div></section>
    <section className={`${s.section} ${s.split}`}><div><h2>From one history<br />to the whole cohort.</h2><p>Compare the same 72 patients at every visit.</p><button className={s.action} onClick={onExplore}>Inspect the timeline <ArrowRight size={17} /></button></div><div><div className={s.chart}>{visitMonths.map(m => <div key={m}><div className={s.stack}>{states.map((state, i) => { const count = syntheticPatients.filter(p => stateFor(p.visits.find(v => v.month === m)!.rate) === state).length; return count > 0 && <span key={state} data-state={i} style={{height: `${count / 72 * 100}%`}} title={`${state}: ${count}`} aria-label={`Month ${m}, ${state}: ${count}`}>{count}</span>; })}</div><small>Month {m}</small></div>)}</div><div className={s.legend}>{states.map((state, i) => <span key={state}><i data-state={i} />{state}</span>)}</div></div></section>
    <div className={s.footer}><small>Fictional visit histories · select a point to inspect its source</small><button onClick={onExplore}>Open the explorer <ArrowRight size={16} /></button></div>
    <details className={s.note}><summary>Presenter notes & sources</summary><p>The displayed outcome is documented frequency at a visit, not continuous seizure freedom or a treatment effect. Unknown visits stay unknown. Notes and records were generated together; no extraction or reconciliation was run on them.</p><p>Event time, documentation time and information availability can differ. A later letter may revise a retrospective history, but cannot supply a prediction made earlier. Repeated mentions need checking before deduplication; conflicts and uncertain dates require review.</p><p>The explorer selects a cohort at one reference visit and follows those same patients across all visits. These summaries are descriptive, not recurrence-risk or survival estimates.</p><p>Background: supplied From clinical letters to longitudinal evidence review, 7 September 2026, pp. 3, 7–8. Its focus is evidence records, reconciled timelines and study-specific analytical tables.</p></details>
  </div>;
}
