import ApplicationIcon from "./ApplicationIcon";
import Image from "next/image";
import { useState } from "react";
import { ArrowRight } from "lucide-react";
import s from "./applicationStories.module.css";
export default function PredictionIntroduction({ onExplore }: { onExplore: () => void }) {
  const [threshold, setThreshold] = useState(50);
  const [showHistories, setShowHistories] = useState(false);
  return <div className={s.story} data-story="prediction">
    <section className={s.hero}><div><span className={s.badge}><ApplicationIcon kind="prediction" />Build a prediction · fictional data</span><h1>From patient histories<br />to risk scores.</h1><p>The history inside the notes can change how a model sees a patient.</p><button className={s.action} onClick={onExplore}>Explore risk scores <ArrowRight size={17} /></button></div><Image className={s.heroIllustration} src="/demo/imagery/prediction-hero-v1.png" alt="Paper sculpture of a researcher studying earlier patient records, separated by a divider from a later outcome." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 55vw" /></section>

    <section className={s.section}><div className={s.historyComparisonHeading}><div><h2>Similar records.<br />Different histories.</h2><p>Age and medication count tell only part of the story.</p></div><button className={s.action} aria-expanded={showHistories} aria-controls="prediction-patient-histories" onClick={() => setShowHistories(!showHistories)}>{showHistories ? "Hide the histories" : "Read the histories"}</button></div><div className={s.patientComparison} id="prediction-patient-histories">{[{ name: "Patient A", values: [8, 4, 1], quote: "Seizures have become less frequent: now one each month." }, { name: "Patient B", values: [1, 4, 8], quote: "Seizures have become more frequent: now eight each month." }].map(patient => <article key={patient.name}><header><Image src="/demo/imagery/candidate-record-v1.png" alt="" width={48} height={48} sizes="48px" /><div><h3>{patient.name}</h3><p>42 years · two medications</p></div></header>{showHistories ? <div className={s.revealedHistory}><div className={s.historyValues} aria-label={`${patient.name}: seizures per month at months 0, 3 and 6`}>{patient.values.map((value, i) => <div key={i}><small>Month {i * 3}</small><strong>{value}</strong><span>per month</span></div>)}</div><blockquote>{patient.quote}</blockquote></div> : <p className={s.historyPrompt}>The structured fields look the same.</p>}</article>)}</div><p className={s.caption}>{showHistories ? "The notes reveal both the current frequency and its direction of change—information a risk model can use." : "Illustrative patient histories"}</p></section>
    <section className={`${s.section} ${s.split}`}><div><h2>Turn the history into model inputs.</h2><dl className={s.predictionFeatures}><div><dt>Structured fields</dt><dd>Age · medication count</dd></div><div><dt>Information from notes</dt><dd>Frequency · change · missingness</dd></div></dl></div><Image className={s.heroIllustration} src="/demo/imagery/prediction-features-v1.png" alt="Structured fields and highlighted evidence from a clinic letter come together in one model-input record." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 55vw" /></section>
    <section className={`${s.section} ${s.split}`}><div><h2>From individual scores<br />to risk groups.</h2><p>A cutoff turns a ranked cohort into groups you can study. Move it to see where this patient belongs.</p></div><div className={s.scoreDemo}><header><div><span>Illustrative risk score</span><strong>60%</strong><p>The score stays fixed.</p></div><Image src="/demo/imagery/prediction-score-v1.png" alt="" width={104} height={104} sizes="104px" /></header><label htmlFor="intro-threshold">Risk-group cutoff <b>{threshold}%</b></label><div className={s.scoreScale}><div className={s.scoreRail}><span style={{ left: `${threshold}%`, width: `${100 - threshold}%` }} /><i style={{ left: "60%" }}><span>Score 60%</span></i></div><input id="intro-threshold" type="range" min="0" max="100" step="5" value={threshold} onChange={e => setThreshold(Number(e.target.value))} aria-valuetext={`${threshold} percent threshold; ${60 >= threshold ? "higher-risk" : "lower-risk"} prediction`} /></div><div className={s.scoreEndpoints}><span>0%</span><span>100%</span></div><div className={s.scoreDecision} data-positive={60 >= threshold} aria-live="polite"><strong>{60 >= threshold ? "Higher-risk group" : "Lower-risk group"}</strong><span>{60 >= threshold ? "Score meets the threshold" : "Score is below the threshold"}</span></div></div></section>
    <div className={s.footer}><div><h2>Open a score. Read the history.</h2><p className={s.caption}>Compare risk scores with and without note features, then inspect the source records.</p></div><button className={s.action} onClick={onExplore}>Explore risk scores <ArrowRight size={17} /></button></div>
    <details className={s.note}><summary>Presenter notes & sources</summary><p>The target is any seizure documented at month 12, using features available through month 6. This differs from seizure risk over the intervening six months. Future visits never enter the features.</p><p>The explorer fits logistic regression on fictional records. Patient-level splitting and training-only standardisation keep fitting separate from evaluation. Unknown month-12 outcomes are excluded from both comparisons. The two patient histories above are authored examples; no risk scores have been fitted to that pair.</p><p>AUC measures ranking; calibration and decision consequences need separate evaluation. The threshold example is authored, not a fitted patient result. Changes in the toy model’s performance reflect the synthetic generator, not clinical predictive value.</p><p>Background: supplied From clinical text to risk prediction review, 7 September 2026. It distinguishes text-derived information, predictive performance and clinical benefit. External validation, calibration and workflow evaluation remain further steps.</p></details>
  </div>;
}
