import ApplicationIcon from "./ApplicationIcon";
import Image from "next/image";
import { useState } from "react";
import { ArrowRight } from "lucide-react";
import s from "./applicationStories.module.css";
export default function PredictionIntroduction({ onExplore }: { onExplore: () => void }) {
  const [showHistories, setShowHistories] = useState(false);
  return <div className={s.story} data-story="prediction">
    <section className={s.hero}><div><span className={s.badge}><ApplicationIcon kind="prediction" />Risk stratification · simulated data</span><h1>Preventing emergency admissions<br />before they happen.</h1><p>Combine routine hospital records with clinical notes to flag patients at high risk of emergency hospital attendance in the next 12 months.</p><button className={s.action} onClick={onExplore}>Explore admission risk <ArrowRight size={17} /></button></div><Image className={s.heroIllustration} src="/demo/imagery/prediction-hero-v2.png" alt="Paper sculpture of a researcher studying earlier records, separated from a later outcome." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 55vw" /></section>
    <section className={s.section}><div className={s.historyComparisonHeading}><div><h2>Same basic record.<br />Opposite clinical trajectories.</h2><p>Age and medication count look identical on paper, but the clinic notes reveal very different levels of urgency.</p></div><button className={s.action} aria-expanded={showHistories} aria-controls="prediction-patient-histories" onClick={() => setShowHistories(!showHistories)}>{showHistories ? "Hide clinical notes" : "Read clinical notes"}</button></div><div className={s.patientComparison} id="prediction-patient-histories">{[{ name: "Patient A", quote: "One focal aware seizure per month, down from four. No tonic-clonic seizures in the past three months. Reports no missed doses." }, { name: "Patient B", quote: "Eight seizures per month, up from four, including three tonic-clonic seizures in the past three months. Reports missed doses most weeks." }].map(patient => <article key={patient.name}><header><Image src="/demo/imagery/candidate-record-v2.png" alt="" width={48} height={48} sizes="48px" /><div><h3>{patient.name}</h3><p>42 years · two medications</p></div></header>{showHistories ? <div className={s.revealedHistory}><blockquote>{patient.quote}</blockquote></div> : <p className={s.historyPrompt}>Structured fields look identical.</p>}</article>)}</div><p className={s.caption}>Notes capture critical warning signs: worsening seizure frequency, convulsive seizures, and missed medication.</p></section>
    <section className={`${s.section} ${s.split} ${s.splitReverse}`}><div><h2>Routine charts miss the warning signs.</h2><p>Standard hospital databases track prior visits and prescriptions, but the most actionable clues live inside clinic letters.</p><dl className={s.predictionFeatures}><div><dt>Hospital database records</dt><dd>Patient age · medication count · past emergency visits</dd></div><div><dt>Clues extracted from clinic notes</dt><dd>Seizure frequency trend · tonic-clonic attacks · medication adherence</dd></div></dl></div><Image className={s.heroIllustration} src="/demo/imagery/prediction-features-v2.png" alt="Structured fields and evidence from a clinic letter combine in a model-input record." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 55vw" /></section>
    <section className={`${s.section} ${s.split}`}><div><h2>Triaging clinic capacity for maximum impact.</h2><p>Care teams only have time to proactively review a limited number of patients. Adding note data re-ranks the priority list so clinicians catch urgent cases before an emergency occurs.</p><p className={s.caption}>Interactive simulation based on co-authored sample records to demonstrate clinical triage workflows.</p></div><Image className={s.heroIllustration} src="/demo/imagery/prediction-review-list-v2.png" alt="Two paper patient rankings with the same three review places. An ochre-tagged patient moves from fourth to second when evidence from clinic notes is added." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 55vw" /></section>
    <div className={s.footer}><div><h2>See how note features change clinical priorities.</h2><p className={s.caption}>Compare the same patients under standard records vs. note-enhanced triage.</p></div><button className={s.action} onClick={onExplore}>Open the risk triage explorer <ArrowRight size={17} /></button></div>
    <details className={s.note}><summary>Research basis &amp; other applications</summary><p>A <a href="https://pubmed.ncbi.nlm.nih.gov/41212874/" target="_blank" rel="noreferrer">2025 cohort study protocol</a> proposes predicting emergency care and epilepsy-related death within one year. This demo illustrates the emergency-care use case with its own arbitrary simulation, not the study&apos;s model.</p><p>Other applications include <a href="https://discovery.ucl.ac.uk/id/eprint/10127330" target="_blank" rel="noreferrer">SUDEP risk stratification</a> and <a href="https://repub.eur.nl/pub/99753/" target="_blank" rel="noreferrer">recurrence after medication withdrawal</a>. Each needs a separate outcome definition and evaluation.</p></details>
  </div>;
}
