import { useState } from "react";
import { ArrowRight, CalendarDays, ChartNoAxesCombined, FileText, Gauge, Plus, ScanText, SlidersHorizontal, Users } from "lucide-react";
import s from "./applicationStories.module.css";
export default function PredictionIntroduction({ onExplore }: { onExplore: () => void }) {
  const [threshold, setThreshold] = useState(50);
  return <div className={s.story} data-story="prediction">
    <section className={s.hero}><div><span className={s.badge}><ChartNoAxesCombined size={15} />Build a prediction · fictional data</span><h1>Earlier records.<br />A later outcome.</h1><p>Can notes through month 6 predict seizure documentation at month 12?</p><button className={s.action} onClick={onExplore}>Try the experiment <ArrowRight size={17} /></button></div><div><div className={s.predictionTime}><div className={s.past}>{[0, 3, 6].map(m => <div key={m}><FileText /><span>Month {m}</span></div>)}</div><div className={s.cutoff}><span>Predict here</span></div><ArrowRight size={20} /><div className={s.future}><CalendarDays /><strong>Month 12</strong></div></div><p className={s.caption}>Earlier inputs → later outcome</p></div></section>
    <section className={s.section}><h2>What do the notes add?</h2><div className={s.featureCompare}><div><Users /><span><strong>Structured fields</strong><small>Age · medication count</small></span></div><Plus size={24} /><div><ScanText /><span><strong>Information from notes</strong><small>Frequency · change · missingness</small></span></div></div></section>
    <section className={`${s.section} ${s.split}`}><div><h2>Learn on one group.<br />Test on another.</h2><p>Same patients and model. Two sets of inputs.</p></div><div className={s.trainTest}><div><h3>Train</h3><div className={s.dots} aria-hidden="true">{Array.from({length:24}, (_, i) => <i key={i} />)}</div><p>Fit the model</p></div><ArrowRight size={20} /><div><h3>Test</h3><div className={s.dots} aria-hidden="true">{Array.from({length:12}, (_, i) => <i key={i} />)}</div><p>Measure performance</p></div></div></section>
    <section className={`${s.section} ${s.split}`}><div><h2>One score.<br />A decision you can adjust.</h2><p>Move the threshold. Watch the prediction change.</p><div className={s.metrics}><div><ChartNoAxesCombined /><strong>Ranking</strong><span>AUC</span></div><div><Gauge /><strong>Probabilities</strong><span>Calibration</span></div><div><SlidersHorizontal /><strong>Decisions</strong><span>False positives & misses</span></div></div></div><div className={s.threshold}><label htmlFor="intro-threshold">Threshold <b>{threshold}%</b></label><input id="intro-threshold" type="range" min="10" max="90" step="5" value={threshold} onChange={e => setThreshold(Number(e.target.value))} /><strong aria-live="polite">{60 >= threshold ? "Positive prediction" : "Negative prediction"}</strong><p>Example score: <b>60%</b> · stays fixed</p><p className={s.caption}>Illustrative score</p></div></section>
    <div className={s.footer}><div><h2>Compare the models.</h2><p className={s.caption}>Add note features. Inspect mistakes. Read the source.</p></div><button className={s.action} onClick={onExplore}>Open the experiment <ArrowRight size={17} /></button></div>
    <details className={s.note}><summary>Presenter notes & sources</summary><p>The target is any seizure documented at month 12, using features available through month 6. This differs from seizure risk over the intervening six months. Future visits never enter the features.</p><p>The explorer fits logistic regression on fictional records. Patient-level splitting and training-only standardisation keep fitting separate from evaluation. Unknown month-12 outcomes are excluded from both comparisons. The dots above illustrate separate groups, not sample counts.</p><p>AUC measures ranking; calibration and decision consequences need separate evaluation. The threshold example is authored, not a fitted patient result. Changes in the toy model’s performance reflect the synthetic generator, not clinical predictive value.</p><p>Background: supplied From clinical text to risk prediction review, 7 September 2026. It distinguishes text-derived information, predictive performance and clinical benefit. External validation, calibration and workflow evaluation remain further steps.</p></details>
  </div>;
}
